### ISSUE TITLE
Downloads interrupted with network error

### ISSUE THREAD

**Issue by SoraNoIseki** [beechit/fal_securedownload#176]
Hi. We have a problem. One of our customers had reported to us that some users could not download files, the downloads were interrupted by the reason "Failed - Network error" in Browser.

So we have made some tests, it did happen many times by downloading big files (> 1 GB):
- Tests with throttling "Slow 3G": Download would be interrupted in 2-5 minutes (7-9 MB downloaded)
- Tests with throttling "Fast 3G" or 200-500 KB/s: Download would be interrupted _sometimes_ while it reached 1010-1100 MB

It happened not all the time, so it is quite difficult to locate the error. Have you any idea about this?

Thx & best regards

---

TYPO3 version: 10.4.23
Extension version: 3.0.0

PHP Info:
PHP v7.2.34
max_execution_time = 600
opcache.force_restart_timeout = 180

Server environments:
Ngnix-Cache is activ

Browsers: Chrome, Firefox

**Comment by joey-beech-it** [comment]
@SoraNoIseki 

I would recommend to time the download kill exactly. 

Mostlikely this is done by either  PHP `max_execution_time`
Or some setting in NGINX, i however do not have much experience with NGINX.

It also could be one of the following settings that kills the download.
https://www.linuxcapable.com/three-examples-to-increase-request-timeout-in-nginx/ 

I am closing this issue since it is not extension related.
